##⇘⇘The following are enhanced function key bindings implemented based on the inputevent.lua script
## '#event:click' specifies the action for a single click of the same key, '#event:double_click' for a double click, '#event:press' for a long press, '#event:release' for release after a long press
## For more key actions, please refer to the script's upstream documentation: https://github.com/zhongfly/InputEvent/tree/property-expansion
##! Note: Not all keys have the above different trigger actions
## The script also supports triggering different commands for the same action based on conditions, with syntax equivalent to profile-cond (conditional statements for auto profiles)
## The script syntax is upgraded to '#event:action|condition' (the original '#event:action' executes the command unconditionally), command execution priority is from bottom to top, executing the first command that meets the condition

RIGHT           seek 5                                        #event:click
RIGHT           script-message-to evafast speedup             #event:press
RIGHT           script-message-to evafast slowdown            #event:release

TAB             script-message-to file_browser browse-files;script-message-to file_browser dynamic/reload;show-text '' #event:click
TAB             script-message-to uosc toggle-ui              #event:press
TAB             script-message-to uosc toggle-ui              #event:release

PGDWN           add chapter -1                                                               #event:click
PGDWN           playlist-prev;show-text Playlist:${playlist-pos-1}/${playlist-count}         #event:click|chapter == 0
PGDWN           playlist-prev;show-text Playlist:${playlist-pos-1}/${playlist-count}         #event:press
PGUP            add chapter  1                                                               #event:click
PGUP            playlist-next;show-text Playlist:${playlist-pos-1}/${playlist-count}         #event:click|chapter+1 == chapters
PGUP            playlist-next;show-text Playlist:${playlist-pos-1}/${playlist-count}         #event:press

SPACE           cycle pause;script-message-to uosc flash-pause-indicator  #event:click
SPACE           script-binding simplehistory/history-load-last            #event:click|idle_active
SPACE           no-osd set speed 3; set pause no                          #event:press
SPACE           ignore                                                    #event:release

MBTN_LEFT       cycle pause;script-message-to uosc flash-pause-indicator  #event:click
MBTN_LEFT       cycle fullscreen                                          #event:double_click