# Set the time interval for automatically saving file playback progress and status, in seconds. Default: 60 seconds
save_interval=60
# Set the percentage of file playback progress at which the saved playback progress and status will be automatically deleted. Default: 99
percent_pos=99