### Comments after parameters are not supported; they must be on a separate line

## Disable all auto-loading related functions, default: no
#disabled=yes

## Whether to automatically load all images in the current directory (excluding subdirectories) into the playlist, default: yes
#images=no

## Whether to automatically load all videos in the current directory (excluding subdirectories) into the playlist, default: yes
#videos=no

## Whether to automatically load all audio in the current directory (excluding subdirectories) into the playlist, default: yes
#audio=no

## Specify additional whitelist extensions for images, videos, and audio to be loaded
additional_image_exts=jfif
additional_video_exts=asf,f4v,rm,ts,vob
additional_audio_exts=dsf,spx

## <auto|recursive|lazy|default ignore> When opening a file, choose to recurse, lazy, or ignore all subdirectories
directory_mode=ignore

## Whether to skip hidden files, default: yes
#ignore_hidden=no

## Specify filename patterns to skip, separated by commas. Default is empty
## Supports Lua pattern syntax; use % to escape commas
#ignore_patterns=^~,^bak-,%.bak$

## Whether to automatically load only files of the same type (video, audio, image), default: no
same_type=yes

## Whether to automatically load only files of a similar series, default: no
#same_series=yes