# Manually specify the absolute path of executable files if the following programs are not in the environment variables

# 1. ffmpeg
#ffmpeg_path=C:/Program Files/ffmpeg/bin/ffmpeg.exe
ffmpeg_path=ffmpeg

# 2. ffsubsync
#ffsubsync_path=C:/Program Files/ffsubsync/ffsubsync.exe
#ffsubsync_path=/home/user/.local/bin/ffsubsync

# 3. alass
#alass_path=C:/Program Files/ffmpeg/bin/alass.exe
#alass_path=/usr/bin/alass
##⇘⇘The following path is set to look for the specified program in the root directory where mpv is located
alass_path=alass

# Preferred subtitle synchronization tool. Allowed options: 'ffsubsync', 'alass', 'ask'.
# If set to "ask", the script will ask to choose the tool each time:

# 1. Preferred tool for synchronizing with audio. ('ffsubsync', 'alass', 'ask')
audio_subsync_tool=alass

# 2. Preferred tool for synchronizing with subtitles. ('ffsubsync', 'alass', 'ask')
altsub_subsync_tool=alass

# Disable the original subtitle (yes, no)
# After attempting subtitle synchronization, tell mpv to ignore the original subtitle track
unload_old_sub=no