# Set either blacklist or whitelist, not both

# Whitelist, only allow video formats
#whitelist=3gp,amr,amv,asf,avi,avi,bdmv,f4v,flv,ifo,iso,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv

# Or, common blacklist formats found near videos
blacklist=mpls,mks,mka,weba,aqt,ass,gsub,idx,jss,lrc,mks,pgs,pjs,psb,rt,slt,smi,sub,sup,sbv,srt,ssa,ssf,ttxt,txt,usf,vt,vtt

remove_files_without_extension=yes

# The script only takes effect at the start of playback. When disabled, it also takes effect when the playlist changes
oneshot=no