# Whether to enable automatic reading and loading of external chapter files. Default: yes
autoload=yes
# Whether to enable automatic export of chapter files (when chapter information changes). Default: no
autosave=no
# Whether to use external chapter information to override internal video chapter information. Default: no
force_overwrite=no
# Specify the identifier and extension for external chapter files
chapter_file_ext=.chp
# Choose whether the external chapter file name needs to match the source file extension. Default: yes
basename_with_ext=yes
# Read external chapter files from the specified subdirectory in the same directory as the video file
# Note: The script prioritizes reading external chapter files from the specified subdirectory
# If the file does not exist in the subdirectory, it will continue to try reading the external chapter file from the same directory as the video file
external_chapter_subpath=chapters
# Whether to uniformly store chapter files in the configured global directory. Network files will always use the global directory. Default: no
global_chapters=no
# Specify the path to the global directory for chapter files. Can be a relative or absolute path supported by mpv
global_chapters_dir=~~/files/chapters
# Whether to save chapter filenames using a hash value in the global directory. Default: no
## If set to 'no', chapter files will be named after the corresponding media file, which may cause conflicts
## Using a hash prevents media files with the same name but located in different directories from obtaining the same chapter file
## However, if you move a file to a different directory, the hash value will change, preventing the chapter file from loading
hash=no
# Set whether to enable the rename input function by default when creating a new chapter. Default: yes
ask_for_title=yes
# Set the placeholder name when asking for a new chapter title
placeholder_title=Chapter 
# Set whether to pause playback when asking for a chapter title. Default: yes
pause_on_input=yes