### This configuration does not support comments after parameters; they must be on a separate line

# Whether to save command history to a file and load it. Default: no
persist_history=yes
# Path to the command history file. Default: ~~state/command_history.txt
history_path=~~/files/command_history.txt