### This configuration does not support comments after parameters; they must be on a separate line

# Specify the monospace font used for completions displayed in the console. Uses --osd-font for other cases
monospace_font=Noto Sans Mono CJK SC
# Font size defaults to 24. The final size will be multiplied by the scale factor
#font_size=24
# Set the font border size for the REPL and console. Default: 1.32
border_size=1.3
# Transparency of the menu background. Range from 0 (opaque) to 255 (fully transparent). Default: 80
background_alpha=50
# Gap between menu items, specified as a percentage of the font size. Default: 0.2
#gap=0.2
# Padding of the menu. Default: 10
#padding=10
# Size of the menu border. Default: 0
#menu_outline_size=0
# Color of the menu border. Default: #FFFFFF
#menu_outline_color=#FFFFFF
# Corner radius of the menu. Default: 8
#corner_radius=8
# Color of the selected menu item. Default: #222222
#selected_color=#222222
# Background color of the selected menu item. Default: #FFFFFF
#selected_back_color=#FFFFFF
# Color of characters matching the search string. Default: #0088FF
#match_color=#0088FF
# Whether to scale the console using the window height. Can be yes, no, or auto, depending on the --osd-scale-by-window option. Default: auto
#scale_with_window=auto
# Whether to use exact search instead of fuzzy search when querying. Default: no
# Prepend the ' character to the query to force exact matching
#exact_match=no
# Set whether Tab auto-completion is case-sensitive. Only applies to ASCII characters
## Default: no on Windows, yes on other platforms
#case_sensitive=no
# Remove duplicate entries in history, keeping only the latest entry. Default: yes
history_dedup=yes
# Set the ratio of font height to font width to adjust the completion suggestion table width. Default: auto
## Values in the range 1.8-2.5 are useful for common monospace fonts
#font_hw_ratio=auto