### Comments after parameters are not supported; they must be on a separate line
### No extra spaces are allowed between options and values
## https://mpv.io/manual/master/#context-menu
# Font size
font_size=20
# Spacing between menu items
gap=0.2
# Horizontal and vertical padding of menu items
padding_x=8
padding_y=4
# Menu border thickness and color
menu_outline_size=0.5
menu_outline_color=#FFFFFF
# Corner radius
corner_radius=5
# Whether to scale the menu synchronously with the window height. <no|yes|default auto>
scale_with_window=auto
# Color and background color of the focused item
focused_color=#222222
focused_back_color=#FFFFFF
# Color of disabled items and separators
disabled_color=#555555
# Delay time for expanding and closing submenus
seconds_to_open_submenus=0.2
seconds_to_close_submenus=0.2