##! Note: This menu script only supports Windows systems
## Specify whether to use mpv's internal context menu implementation. Default is yes
## Requires an mpv version that includes the upstream commit https://github.com/mpv-player/mpv/commit/3c1e983
use_mpv_impl=yes
### Specify whether to enable uosc menu syntax support. Incompatible with the default supported mpv.net menu syntax, but allows using uosc menu syntax. Default is no
uosc_syntax=yes
## Specify whether to enable menu title escaping. Default is yes
escape_title=yes
## Specify the maximum length of the menu title. Default is 80. If the title length exceeds this value, it will be truncated
## Set to 0 to disable title length limit
max_title_length=80
## Specify the maximum number of playlist menu items. Default is 20
## Set to 0 to disable the playlist menu
max_playlist_items=20