# How far to seek when a script key is pressed
seek_distance=5

# Playback speed adjustment amount, applied every 'speed_interval' until the upper limit is reached
speed_increase=0.1
speed_decrease=0.1

# Interval at which to apply the speed adjustment amount
speed_interval=0.05

# Playback speed upper limit
speed_cap=3

# Playback speed upper limit when subtitles are displayed. 'no' means same as 'speed_cap'
subs_speed_cap=1.5

# Multiply the current speed by the speed adjustment amount before adjusting (exponential acceleration). Default: no
# Use much lower values than the defaults, e.g., speed_increase=0.05, speed_decrease=0.025
multiply_modifier=no

# Display the current speed on the OSD (if using uosc, flash the speed). Default: yes
show_speed=yes

# Display the current speed on the OSD when toggling speed (if using uosc, flash the speed). Default: yes
show_speed_toggled=yes

# Display seek operations on the OSD (if using uosc, flash the timeline). Default: yes
show_seek=yes

# Look ahead when setting the 'subs_speed_cap' item for smoother transitions. Default: no
subs_lookahead=no

# Set the symbols for OSD message display. The example shows the default values
#osd_symbol={\fnmpv-osd-symbols} {\r}
#osd_rewind={\fnmpv-osd-symbols} {\r}