# Specify the working mode of the script. Three modes are available: noth, pass, switch. Default: noth
## noth: Do nothing
## pass: When the display is in HDR mode, pass HDR signals for HDR content
## switch: Automatically switch between HDR mode and SDR mode on the display based on the video content played by mpv. Available on Windows 10 and later versions
hdr_mode=noth
# Specify whether to automatically switch HDR mode only when fullscreen or window is maximized. Only takes effect when hdr_mode=switch. Default: no
fullscreen_only=no
# Used to specify the target peak luminance of your HDR display. Default: 203
#! Reminder: This must be set to the actual peak luminance of the display, otherwise HDR content will be displayed incorrectly. The default value 203 will be treated as an SDR display.
target_peak=203
# Used to specify the maximum contrast value of your HDR display. Default: auto, meaning infinite contrast (OLED)
#! Reminder: This must be set to the maximum contrast of the display, otherwise black point compensation cannot be applied correctly.
## For example, 100000 indicates the display's maximum contrast ratio is 100000:1.
## OLED displays do not need to change this value; the default can be used.
target_contrast=auto