## Whether to enable script functionality, default: yes
enabled=yes
## Specify the language for script OSD messages, default: eng
language=eng
## Specify the timeout for script OSD message display, in seconds. Default: 15
timeout=15
## Save record delay time, in milliseconds
#save_period=30
## Save path for video directory playback record files
## Use '/:dir%mpvconf%' or '~~/' to specify the portable_config directory, or use '/:dir%script%' to specify the script directory
## Or use '/:var' to specify an environment variable, e.g., '/:var%APPDATA%' or '/:var%HOME%', or directly use an absolute path
history_dir=/:var%APPDATA%/mpv/files/historybookmarks
## File extension for directory playback record files
bookmark_ext=.mpv.history
## Use a hash value to save record files for playback directories, default: yes
hash=yes
## Specify whether to use playlist information. When disabled, playlist information will be guessed from the directory of the playing file. Default: yes
use_playlist=yes
## Whitelist of file extensions for directory lookup
whitelist=3gp,amr,amv,asf,avi,avi,bdmv,f4v,flv,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv
## Specify to only create history record files within the following paths/directories
#included_dir=[]
## Specify paths/directories of shared drives (mounted drives) to ignore. Windows example: excluded_dir=["X:", "Z:", "F:/Download/", "Download"]
#excluded_dir=[]