# Whether to use an external configuration file for enhanced key actions, default: no
enable_external_config=yes
# Specify the path to the external configuration file, can be a relative or absolute path supported by mpv
# Note: When enabling the external configuration file feature, ensure the file exists
external_config=~~/inputevent_key.conf
# Specify the recognition prefix for key events, default: event
prefix=event