## Specify the animated image format for ffmpeg to capture, options: webp, gif (default)
#type=webp
# Absolute path to ffmpeg, or place it in the environment variable
#ffmpeg_path=ffmpeg
# Set the output directory, default value: ~~desktop/
dir=~~/files/animated
# Set the output resolution, default length is 600
#rez=1280
# Set the output frame rate, default value is 15
#fps=24
# The default is set to 0 (lossy). Change to 1 for lossless. When outputting lossless, it will no longer determine quality, but encoding efficiency. webp only
lossless=0
# Set the quality level percentage, which will determine the quality of webp. It is not recommended to go below 85. webp only
quality=85
# The default value is 6. This process may take a while, so if you don't want to wait, you should lower it, but the lower the value, the larger the file size. webp only
compression_level=3
# Set the number of loops for the animated image, default value 0 means infinite loop
loop=0