## PiP 窗口大小，语法参见： https://mpv.io/manual/stable/#options-autofit
## 例如： 25%x25% 400x300
autofit=25%x25%
## 禁用画中画功能时的 autofit-larger 大小。最好和 mpv.conf 中的--autofit-larger 选项保持一致。默认值：100%x100%
autofit_restore_larger=100%x100%
## 禁用画中画功能时的 autofit-smaller 大小。最好和 mpv.conf 中的--autofit-smaller 选项保持一致。默认值：40%x30%
autofit_restore_smaller=40%x30%
## 启用画中画 (PiP) 时的窗口位置。默认值： 100%:100% (右下角)。语法参见： https://mpv.io/manual/stable/#options-geometry
geometry=100%:100%
## 禁用画中画功能时的窗口位置。默认值：50%:50% (居中)
geometry_restore=50%:50%
## 窗口位置延迟（以秒为单位）以避免任何竞速问题
geometry_delay=0.02