# Specify whether to enable the script function, default: yes
#! Note: This option can be changed at runtime
enabled=yes
# Specify the file path for the recent playback history saved by the uosc plugin script recentmenu. Can be a relative or absolute path supported by mpv
path=~~/files/recent.json
# Specify the menu title displayed when opening the script menu
title=Recent Playback
# Specify the maximum number of recent playback history entries to save. Default: 10
length=20
# Specify the character limit for the recent playback menu entries in uosc. Default: 88
width=70
# Whether to record only the last played entry of files in the same series within the same directory. Default: yes
# When enabled, only the last played entry of files in the same series within the same directory will be recorded. This is identified by similarity, which may lead to false positives
ignore_same_series=yes