# Set the service address for obtaining sponsor segments for YouTube
#youtube_sponsor_server=https://sponsor.ajay.app/api/skipSegments
# Set the service address for obtaining sponsor segments for Bilibili
#bilibili_sponsor_server=https://bsbsb.top/api/skipSegments
# Specify the categories to fetch and skip
#categories="sponsor"