# API token, can be obtained on the personal page after registering an account at https://assrt.net
# The example is a preset key within the script
#api_token=tNjXZUnOJWcHznHDyalNMYqqP6IdDdpQ
# Whether to use https, default yes
#use_https=no
# Proxy settings
#proxy=