# Path to the faster-whisper executable, supports absolute and relative paths
# Can be downloaded from: https://github.com/Purfview/whisper-standalone-win
#fast_whisper_path=faster-whisper
# Specify the model to use. Available models: base, small, medium, large, turbo
#model=large-v3
# Specify the device to use. Available devices: cpu, cuda
#device=cuda
# Specify the language for transcribing speech. Leave empty for auto-detection
#language=ja
# Specify the number of CPU threads to use
# Default is 0, which will auto-detect, but with a maximum of 4 threads
#threads=8
# Maximum number of characters per line before a line break
max_line_width=100
# Specify the output path, supports absolute and relative paths
# Special value: "source" will save the subtitle file to the directory where the video file is located
output_path=source
# Specify how many subtitles to generate before updating. Used to avoid frequent subtitle flickering
update_interval=20
# Use segmentation for speech transcription, which greatly increases the speed of subtitle initialization
# But reduces the accuracy and overall speed of subtitle generation, more suitable for long video scenarios
#! Depends on FFmpeg
use_segment=no
# Segment duration in seconds
segment_duration=10
## GPT API Options ###
# Compatible with any AI API that has the same structure as the GPT API
# The free AI model from Zhipu GLM is recommended: glm-4-flash
api_url=https://open.bigmodel.cn/api/paas/v4/chat/completions
# api key needs to be applied for on the personal account page of the corresponding AI platform
api_key=
# Specify the AI model to use
api_mode=glm-4-flash
api_temperature=0.95
# Rate per minute for API usage. See the corresponding API documentation for instructions
api_rate=15
# Specify the target language for AI translation
translate=Chinese
# Specify the font name for the generated ass subtitles
font_name=Noto Sans CJK SC