# Absolute path to ffmpeg, or place it in the environment variable
ffmpeg_path=ffmpeg
# Specify the language for text displayed by the script on OSD and console. eng=English, chs=Chinese. Default: eng
language=eng