# Socket path (leave empty for automatic setting)
socket=

# Thumbnail cache path (leave empty for automatic setting)
thumbnail=

# Maximum thumbnail size (in pixels) (scaled down to fit)
# When hidpi is enabled, this value will be scaled adaptively
max_height=200
max_width=200

# Overlay ID
overlay_id=42

# Spawn the thumbnailer when the file is loaded for faster initial thumbnails. Disabled by default
spawn_first=no

# Whether to quit the thumbnailer process after inactivity timeout (seconds). Default 0 disables
quit_after_inactivity=0

# Enable when playing network content. Disabled by default
network=no

# Enable when playing audio. Disabled by default
audio=no

# Enable hardware decoding for thumbnail generation. Disabled by default
# Note: Hardware decoding can accelerate thumbnail generation on high-end graphics cards, but may cause issues on low-end ones
hwdec=yes

# Windows only: Use native Windows API for writing to pipes (requires LuaJIT). Disabled by default
direct_io=yes

# Specify a custom path to the mpv executable. Default: mpv
mpv_path=mpv

# Specify a blacklist of video extensions to ignore, as these files cannot generate thumbnails properly
blacklist_ext=bdmv,ifo

## Specify paths/directories of shared drives (mounted drives) to ignore (poor thumbnail generation performance)
## Windows example: excluded_dir=["X:", "Z:", "F:/Download/", "Download"]
#excluded_dir=[]