# Options are slash-separated lists of words and languages
##是否启用脚本，默认 yes
enabled=yes
##同步选择曲目，与其他脚本一起更好地工作，默认 yes
hook=yes
##模仿 mpv 的曲目列表信息，以保留用户在文件中选择的曲目，默认 no
#fingerprint=yes
##覆盖用户的显式曲目选择，默认 no
#force=yes
##记忆并在后续播放中继承用户手动选择的轨道匹配，默认 no
smart_keep=yes

##视频轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
#preferred_video_lang=
#excluded_video_words=
#expected_video_words=

##音频轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
preferred_audio_lang=japanese/j[ap]n?/english/en%-us/eng?
preferred_audio_channels=8/6/3/2
excluded_audio_words=commentary/cast/staff/dub/guide
expected_audio_words=

##字幕轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
preferred_sub_lang=chs/sc$/zh%-cn/zh%-Hans/cht/tc$/zh%-Hant/zh%-hk/zh%-tw/chi/zho?
excluded_sub_words=sing/song/comment/danmaku/danmu/xml/弹幕
expected_sub_words=chs&j[ap]n?/sc&j[ap]n?/cht&j[ap]n?/ch&j[ap]n?/tc&j[ap]n?/zh&j[ap]n?/chs&eng?/sc&eng?/cht&eng?/ch&eng?/tc&eng?/zh&eng?/zho?%-cn/zho?%-hans/zho?%-hant/zho?%-hk/zho?%-tw/中日/中英/中上英下/特效/简英/简体&英文/繁英/繁体&英文/繁體&英文/简日/繁日/双语/雙语/简/繁/中/simplified/traditional
