# Options are slash-separated lists of words and languages
# Whether to enable the script, default yes
enabled=yes
# Synchronize track selection to work better with other scripts, default yes
hook=yes
# Mimic mpv's track list information to preserve user-selected tracks in the file, default no
# Note: This must be set to no, otherwise the script functionality cannot truly take effect
fingerprint=no
# Override the user's explicit track selection, default no
force=no
# Try to reselect the last track if mpv fails to do so, e.g., when information changes, default no
smart_keep=no
## Specify special protocols to ignore
special_protocols=["://", "^magnet:"]

# Video track filter settings
#preferred_video_lang=
#excluded_video_words=
#expected_video_words=

# Audio track filter settings
preferred_audio_lang=japanese/jpn/jap/ja/jp/english/eng/en
preferred_audio_channels=8/6/3/2
excluded_audio_words=commentary/cast/staff/dub/guide
expected_audio_words=

# Subtitle track filter settings
#preferred_sub_lang=chs/sc/zh-CN/zh-Hans/cht/tc/zh-Hant/zh-HK/zh-TW/chi/zh
#excluded_sub_words=
#expected_sub_words=zh-jp/zh-en/zh-en-sub/bilingual/effect/sc/tc/zh