# Whether to enable the trakt watch history feature, default yes
enabled=no
# Specify the save path for the trakt configuration file, supports absolute or relative paths. Default is ~~/trakt_config.json
# Use '/:dir%script%' to specify the script directory
# Or use '/:var' to specify an environment variable, e.g., '/:var%APPDATA%' or '/:var%HOME%'
config_path=~~/files/trakt_config.json
# Specify the path for the trakt watch history file, supports absolute or relative paths. Default is ~~/trakt_history.json
# Correct trakt association errors by modifying the file content
history_path=~~/files/trakt_history.json
# Set the maximum number of characters to display when truncating long list titles, default: 100
max_title_length=100
# Specify the client_id and client_secret to be used by the trakt api, https://trakt.tv/oauth/applications
# Base64 encoding is also required
client_id=MmU5ZDg5MDcyYmIxNThlZWZhZmNlNTA5ZjZiMWJmMzM3MzcwMTQwMDU4ODFlZGZiYjgzZWI3ZGRkMWMwNGY1YQ==
client_secret=MDcxYTUzZTVkZDhkODA1NTM2MTU2YWNlZTJjYjU5Njc5YjUwOTAwZWU3YmZkYmVmMTZiNGZmODdkMzQ2NGFiNg==
# Specify the OAuth2 redirect URI, must be consistent with the application settings
redirect_uri=https://zapp.com