## Specify the danmaku server address. Custom services need to be compatible with dandanplay's API
## Multiple ordered api_server addresses can be specified, separated by English commas
## Supports using '|' or '#' to separate comments for each item, e.g., "https://a.example.com|Backup A" or "https://b.example.com#Backup B"
api_server=https://api.dandanplay.net
## Specify the fallback server address for obtaining danmaku from Bilibili, iQiyi, Tencent, and Youku, mainly used for obtaining non-anime danmaku
## Available: https://api.danmu.icu, https://dmku.hls.one
#fallback_server=https://api.danmu.icu
## Set the API Key for tmdb, used to obtain Chinese information for non-anime entries (when the search content is non-Chinese)
## You can register at https://www.themoviedb.org and obtain it from the personal account settings page
## Note: When customizing this parameter, you also need to base64 encode the obtained API Key
#tmdb_api_key=NmJmYjIxOTZkNzIyN2UyMTIzMGM3Y2YzZjQ4MDNkZGM=
## Automatically load network danmaku
auto_load=no
## Automatically load local danmaku
autoload_local_danmaku=no
## Automatically load danmaku for URL streaming playback scenarios
autoload_for_url=yes
## Automatically save network danmaku locally (as an xml file with the same name in the same directory as the video)
save_danmaku=no
## Enable fps video filter to make danmaku scrolling smoother
##! High performance cost
#vf_fps=yes
## Set the fps filter parameters to use
#fps=60/1.001
## Specify the tolerance value for the time interval for merging duplicate danmaku, in seconds. Default: -1, meaning disabled
merge_tolerance=0
## Whether to ignore style and color differences when merging duplicate danmaku. Default: no
#merge_without_style=yes
## Limit the maximum number of danmaku displayed on the same screen. Default value 0 means no limit
max_screen_danmaku=0
## Specify the path for the danmaku association history file, supports absolute and relative paths
history_path=~~/files/danmaku-history.json

## Chinese simplified/traditional conversion. 0-no conversion, 1-convert to simplified, 2-convert to traditional
chConvert=0
## Display time for scrolling danmaku. This affects the scrolling speed
scrolltime=15
## Display time for fixed danmaku
fixtime=5
## Font name
fontname=Microsoft YaHei
## Font size
fontsize=50
## Opacity
opacity=0.6
## Bold
bold=yes
## Outline (0-4)
outline=1
## Shadow
shadow=0
## Display area for all danmaku (0.0-1.0)
displayarea=0.85

## Specify the path to the danmaku blocklist file (black.txt), supports absolute and relative paths. File content is separated by newlines
## Supports Lua regular expression syntax
#blacklist_path=
## Additional replacement rules for custom title parsing. The content format is a JSON string, and the replacement mode uses Lua's string.gsub function
##! Note: Due to mpv's Lua version limitations, custom rules only support capture group syntax like %n, as shown in the example usage. Direct character replacement syntax is not supported
title_replace=[{"rules":[{ "^〔(.-)〕": "%1"},{ "^.*《(.-)》": "%1" }]}]
## Specify paths/directories of shared drives (mounted drives) to ignore in hash matching. Supports absolute and relative paths. Multiple paths are separated by commas
## Example: ["X:", "Z:", "F:/Download/", "Download"]
#excluded_path=