# Specify the port to be used by the webui. Default: 8080
# The webui can be accessed within the local area network via http://[::1]:port (ipv6) or local IP:port (ipv4)
port=8060
# Whether to disable the webui. Default: no
disable=no
# Whether to log requests to standard output. Default: no
logging=no
# Whether to log to OSD. Default: yes
osd_logging=yes
# Whether to enable listening on ipv4. Default: yes
ipv4=yes
# Whether to enable listening on ipv6. Default: yes
ipv6=no
# Specify the audio device used for cycling. Leave empty to use all interfaces known to MPV
#audio_devices=
# Specify the directory for webui frontend static files. Used to customize the frontend UI of the webui
# The provided path can be absolute or relative. Leave empty by default
#static_dir=
# Specify the path to the authentication file. Leave empty by default. Refer to https://github.com/open-dynaMIX/simple-mpv-webui#htpasswd_path
# Relative paths are searched relative to the program's current working directory, so it's best to always use absolute paths
#htpasswd_path=
# To use the basic file browser API in the webui, configure the absolute paths of the directories to be exposed here (separated by ;). Leave empty by default
# Example: collections=/home/user/Music;/home/user/Videos
#collections=