### Comments after parameters are not supported; they must be on a separate line

## Prefer to use ytdl to parse URLs first (default no). Depends on whether most URL playback scenarios require ytdl parsing
try_ytdl_first=yes

## URL parsing address blacklist. For format explanation, see https://mpv.io/manual/master/#options-exclude
## Recommended for use when try_ytdl_first=yes, can reasonably accelerate the parsing of network addresses
exclude=%.avi$|%.flac$|%.flv$|%.mp3$|%.m3u$|%.m3u8$|%.m4a$|%.m4v$|%.mkv$|%.mp4$|%.ts$|%.VOB$|%.wav$|%.webm$|%.wmw$

## When try_ytdl_first is no, the list of URL patterns that mpv should attempt to parse using ytdl first. Matching method is the same as exclude. The example shows the default value
include=^%w+%.youtube%.com/|^youtube%.com/|^youtu%.be/|^%w+%.twitch%.tv/|^twitch%.tv/

## https://mpv.io/manual/master/#options-all-formats
#all_formats=no
#force_all_formats=yes

## Allow switching source tracks (disabled by default for performance reasons)
#use_manifests=no

## The most active branch of youtube-dl, yt-dlp, has a strong trend of replacing the upstream and is actively developed. https://github.com/yt-dlp/yt-dlp/releases
## youtube-dl.exe / yt-dlp.exe must be in the environment variable PATH, or in the directory where mpv.exe is located
## yt-dlp.exe update command: yt-dlp -U
#ytdl_path=yt-dlp